### PR TITLE
Fixes typo in description

### PR DESCRIPTION
**Pull request by bsonntag**
"two dates is" => "two dates are"

### CODE REVIEW

**Comment by kevva** [comment]
Can you update [this](https://github.com/kevva/compare-week/blob/master/package.json#L4) too?

**Comment by bsonntag** [comment]
What do you mean? What does that imagemin-optipng issue have to do with this?

**Comment by kevva** [comment]
Oops, pasted the wrong link. I meant https://github.com/kevva/compare-week/blob/master/package.json#L4.

**Comment by bsonntag** [comment]
@kevva Done.

**Comment by kevva** [comment]
Thanks!

**Pull request merged**
